export const SURVEY_QUESTIONS = [
  {
    question_number: 1,
    section: "Community Health Perception",
    question_text: "What are the most important factors for a healthy community?",
    response_type: "open_ended" as const,
  },
  {
    question_number: 2,
    section: "Community Health Perception",
    question_text: "What are the most important health problems in Franklin?",
    response_type: "open_ended" as const,
  },
  {
    question_number: 3,
    section: "Community Health Perception",
    question_text: "What risky behaviors have the biggest impact on community health?",
    response_type: "open_ended" as const,
  },
  {
    question_number: 4,
    section: "Community Health Perception",
    question_text: "Rate Franklin as a healthy community (1-5)",
    response_type: "scale" as const,
    scale_min: 1,
    scale_max: 5,
    scale_min_label: "Very Unhealthy",
    scale_max_label: "Very Healthy",
  },
  {
    question_number: 5,
    section: "Community Connectedness",
    question_text: "How connected do you feel to the Franklin community? (1-5)",
    response_type: "scale" as const,
    scale_min: 1,
    scale_max: 5,
    scale_min_label: "Not Connected",
    scale_max_label: "Very Connected",
  },
  {
    question_number: 6,
    section: "Community Connectedness",
    question_text: "Do you feel seen and heard in your community?",
    response_type: "yes_no" as const,
  },
  {
    question_number: 7,
    section: "Community Connectedness",
    question_text: "What would help you feel more connected?",
    response_type: "open_ended" as const,
  },
  {
    question_number: 8,
    section: "Mental & Behavioral Health",
    question_text: "Rate your access to mental health resources (1-5)",
    response_type: "scale" as const,
    scale_min: 1,
    scale_max: 5,
    scale_min_label: "Very Poor",
    scale_max_label: "Excellent",
  },
  {
    question_number: 9,
    section: "Mental & Behavioral Health",
    question_text: "Have you or family had difficulty accessing mental health services in past 12 months?",
    response_type: "yes_no" as const,
  },
  {
    question_number: 10,
    section: "Mental & Behavioral Health",
    question_text: "What barriers have you experienced accessing mental/behavioral health support?",
    response_type: "open_ended" as const,
  },
  {
    question_number: 11,
    section: "Physical Activity & Nutrition",
    question_text: "How many days per week do you exercise for 30+ minutes?",
    response_type: "multiple_choice" as const,
  },
  {
    question_number: 12,
    section: "Physical Activity & Nutrition",
    question_text: "Rate your access to affordable healthy food (1-5)",
    response_type: "scale" as const,
    scale_min: 1,
    scale_max: 5,
    scale_min_label: "Very Poor",
    scale_max_label: "Excellent",
  },
  {
    question_number: 13,
    section: "Healthcare Access",
    question_text: "Rate your own personal health (1-5)",
    response_type: "scale" as const,
    scale_min: 1,
    scale_max: 5,
    scale_min_label: "Very Unhealthy",
    scale_max_label: "Very Healthy",
  },
  {
    question_number: 14,
    section: "Healthcare Access",
    question_text: "Where do you go first when sick?",
    response_type: "multiple_choice" as const,
  },
  {
    question_number: 15,
    section: "Demographics",
    question_text: "Age range and zip code",
    response_type: "demographic" as const,
  },
] as const;

export type QuestionResponseType = (typeof SURVEY_QUESTIONS)[number]["response_type"];
